// This is a stub file to allow the project to build
// In a real deployment with Convex properly configured, this would be generated by convex codegen

// Export a minimal api object that satisfies the imports
export const api = {
  surveys: {
    submitSurvey: () => ({} as any),
    getSocieties: () => ({} as any),
    getBySurveyor: () => ({} as any),
    getAll: () => ({} as any)
  },
  users: {
    createUser: () => ({} as any),
    updateUser: () => ({} as any),
    deleteUser: () => ({} as any)
  },
  wallet: {} as any,
  bookings: {} as any,
  http: {} as any
} as any;

// Export internal for compatibility
export const internal = {} as any;

// Export components for compatibility
export const components = {};

// Export ApiFromModules for compatibility
export const ApiFromModules = {} as any;
