/* eslint-disable */
/**
 * This file was automatically generated by Convex.
 * Do not manually edit this file.
 */

/* Generated by convex encode: @convex-dev/codegen@0.1.89 */
import { filterApi } from "convex/server";
import * as bookings from "../bookings.ts";
import * as http from "../http.ts";
import * as users from "../users.ts";
import * as wallet from "../wallet.ts";
import * as surveys from "../surveys.ts";

const fullApi = filterApi({
  bookings,
  http,
  users,
  wallet,
  surveys,
});

export const api = fullApi;
export const internal = fullApi;

// TODO(tap): This is a temporary workaround until we ship components
export const components = {};

export { filterApi as ApiFromModules };
