// This is a stub file to allow the project to build
// In a real deployment with Convex properly configured, this would be generated by convex codegen

// Export the Id type that is being imported by admin/page.tsx and other files
// In Convex, Id<T> is a branded string, but for building we use string
export type Id<TableName extends string> = string;

// Enhanced types based on actual usage in the codebase
// Import the BookingStatus from our shared types to ensure consistency
export type BookingStatus = 
  | "pending"
  | "confirmed"
  | "in-progress"
  | "completed"
  | "cancelled";

export type Booking = {
  _id: string;
  userId: string;
  serviceName: string;
  date: number; // timestamp
  time: string;
  amount: number;
  address: string;
  tankSize?: string;
  tankType?: string;
  status: BookingStatus;
  paymentStatus: string;
  createdAt?: number;
  updatedAt?: number;
};

export type Survey = {
  _id: string;
  // Add survey properties as needed
};

export type Society = {
  _id: string;
  // Add society properties as needed
};

export type User = {
  _id: string;
  clerkId: string;
  name?: string;
  phoneNumber?: string;
  role?: string;
  walletBalance?: number;
  createdAt?: number;
  updatedAt?: number;
};

export type Wallet = {
  _id: string;
  balance: number;
  userId: string;
  updatedAt?: number;
};

// Also export the other types that might be needed
export type TableNames = "bookings" | "surveys" | "societies" | "users" | "wallet";
export type Doc<TableName extends TableNames> = 
  TableName extends "bookings" ? Booking :
  TableName extends "surveys" ? Survey :
  TableName extends "societies" ? Society :
  TableName extends "users" ? User :
  TableName extends "wallet" ? Wallet :
  { _id: string };

export type DataModel = {
  bookings: Booking[];
  surveys: Survey[];
  societies: Society[];
  users: User[];
  wallet: Wallet[];
};

export type SystemTableNames = never;
