/* eslint-disable */
/**
 * This file was automatically generated by Convex.
 * Do not manually edit this file.
 */

/* Generated by convex encode: @convex-dev/codegen@0.1.89 */
import {
  GenericId,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNames,
  DataModelFromSchemaDefinition
} from "convex/server";
import schema from "../schema.ts";

/**
 * The names of all of your Convex tables.
 */
exports.TableNames = /*#__PURE__*/(function () {
  const tableNamesInDataModel = DataModelFromSchemaDefinition(schema)
    .tableNames;
  return tableNamesInDataModel;
})();
/**
 * The type of a document stored in Convex.
 *
 * @typeParam TableName - A string literal type of the table name (like "users").
 */
exports.Doc = /*#__PURE__*/function (TableName) {
  return /*#__PURE__*/DocumentByName(TableName);
};
/**
 * Generic ID type for referencing documents.
 */
exports.Id = /*#__PURE__*/function (TableName) {
  return /*#__PURE__*/GenericId(TableName, "_id");
};
/**
 * The names of system tables in Convex.
 */
exports.SystemTableNames = /*#__PURE__*/(function () {
  const systemTableNames = DataModelFromSchemaDefinition(schema)
    .systemTableNames;
  return systemTableNames;
})();
