// This is a stub file to allow the project to build
// In a real deployment with Convex properly configured, this would be generated by convex codegen

// Export simplified function signatures to avoid TypeScript errors
// These match what the convex/* files expect when importing from ./_generated/server
export const query = <T extends any>(options: T) => {
  return {
    _implementation: () => {}
  } as any;
};

export const mutation = <T extends any>(options: T) => {
  return {
    _implementation: () => {}
  } as any;
};

export const action = <T extends any>(options: T) => {
  return {
    _implementation: () => {}
  } as any;
};

export const httpAction = <T extends any>(options: T) => {
  return {
    _implementation: async () => new Response()
  } as any;
};

// Internal variants
export const internalQuery = <T extends any>(options: T) => {
  return {
    _implementation: () => {}
  } as any;
};

export const internalMutation = <T extends any>(options: T) => {
  return {
    _implementation: () => {}
  } as any;
};

export const internalAction = <T extends any>(options: T) => {
  return {
    _implementation: () => {}
  } as any;
};

export const internalHttpAction = <T extends any>(options: T) => {
  return {
    _implementation: async () => new Response()
  } as any;
};

// Export types for compatibility (these won't cause runtime errors in JS)
export type MutationCtx = any;
export type QueryCtx = any;
export type InternalMutationCtx = any;
export type InternalQueryCtx = any;
export type ActionCtx = any;
export type InternalActionCtx = any;
export type Db = any;
export type DbMutation = any;
export type InternalDb = any;
export type InternalDbMutation = any;
