/* eslint-disable */
/**
 * This file was automatically generated by Convex.
 * Do not manually edit this file.
 */

/* Generated by convex encode: @convex-dev/codegen@0.1.89 */
import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
// Import DataModel separately (without type keyword for JS compatibility)
import { DataModel } from "./dataModel.ts";

/**
 * Define a query in this Convex app's public API.
 *
 * This function will be allowed to read your Convex database and will be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myQuery = query(({ db }) => {
 *   return db.query("myTable").collect();
 * });
 * ```
 */
export const query = ((null) );

/**
 * Define a query that is only accessible from other Convex functions (but not from the client).
 *
 * This function will be allowed to read from your Convex database. It will not be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myQuery = internalQuery(({ db }) => {
 *   return db.query("myTable").collect();
 * });
 * ```
 */
export const internalQuery = ((null) );

/**
 * Define a mutation in this Convex app's public API.
 *
 * This function will be allowed to modify your Convex database and will be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myMutation = mutation(({ db }, args) => {
 *   db.insert("myTable", { ...args });
 * });
 * ```
 */
export const mutation = ((null) );

/**
 * Define a mutation that is only accessible from other Convex functions (but not from the client).
 *
 * This function will be allowed to modify your Convex database. It will not be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myMutation = internalMutation(({ db }, args) => {
 *   db.insert("myTable", { ...args });
 * });
 * ```
 */
export const internalMutation = ((null) );

/**
 * Define an action in this Convex app's public API.
 *
 * This function will be allowed to run arbitrary code and will be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myAction = action(async ({}) => {
 *   return "Hello World";
 * });
 * ```
 */
export const action = ((null) );

/**
 * Define an action that is only accessible from other Convex functions (but not from the client).
 *
 * This function will be allowed to run arbitrary code. It will not be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myAction = internalAction(async ({}) => {
 *   return "Hello World";
 * });
 * ```
 */
export const internalAction = ((null) );

/**
 * Define an HTTP action in this Convex app's public API.
 *
 * This function will be allowed to handle HTTP requests and will be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myHttpAction = httpAction(async ({ request }) => {
 *   return { body: "Hello World", status: 200 };
 * });
 * ```
 */
export const httpAction = ((null) );

/**
 * Define an HTTP action that is only accessible from other Convex functions (but not from the client).
 *
 * This function will be allowed to handle HTTP requests. It will not be accessible from the client.
 *
 * Usage:
 * ```js
 * export const myHttpAction = internalHttpAction(async ({ request }) => {
 *   return { body: "Hello World", status: 200 };
 * });
 * ```
 */
export const internalHttpAction = ((null) );

/* Note: The following type exports are for TypeScript only and would cause errors in JavaScript.
 * They are omitted here since this is a .js file that should be compatible with both JS and TS.
 * In a real Convex codegen, these would be in a separate .d.ts file or handled differently.
 */
// export type MutationCtx = GenericMutationCtx<DataModel, "public">;
// export type QueryCtx = GenericQueryCtx<DataModel, "public">;
// export type InternalMutationCtx = GenericMutationCtx<DataModel, "internal">;
// export type InternalQueryCtx = GenericQueryCtx<DataModel, "internal">;
// export type ActionCtx = GenericActionCtx<DataModel, "public">;
// export type InternalActionCtx = GenericActionCtx<DataModel, "internal">;
// export type Db = GenericDatabaseReader<DataModel, "public">;
// export type DbMutation = GenericDatabaseWriter<DataModel, "public">;
// export type InternalDb = GenericDatabaseReader<DataModel, "internal">;
// export type InternalDbMutation = GenericDatabaseWriter<DataModel, "internal">;
